サイドナビゲーション・フッター作成
camp-team/yama-portal-2 pull request #22
Opened 2020-05-08 02:48 UTC by hide-a1

#8 #9 

## details
サイドナビゲーションの教材とCAMPのサイトをほぼパクっていますが、一応できました。
ご確認お願いいたします。

## image
![image](https://user-images.githubusercontent.com/60844124/81364774-70c30a00-9121-11ea-9849-156e5cdd04d6.png)

2020-05-08 04:06 UTC, dninomiya requested changes

2020-05-08 04:06 UTC, deerboy commented on src/app/home/home/home.component.scss
> +.copyright[_ngcontent-gmv-c130] {
この属性は不要

2020-05-08 04:06 UTC, deerboy commented on src/app/home/home/home.component.scss
> +user agent stylesheet p {
？

2020-05-08 04:13 UTC, hide-a1 commented on src/app/home/home/home.component.scss
> +.copyright[_ngcontent-gmv-c130] {
CAMPのサイトの検証画面からスタイルを雑にコピペしてました。
すみません！

2020-05-08 04:25 UTC, hide-a1 commented on src/app/home/home/home.component.scss
> +.copyright[_ngcontent-gmv-c130] {
修正いたしました。ご確認お願いいたします。

2020-05-08 04:36 UTC, deerboy commented on src/app/home/home/home.component.scss
> +  margin-block-start: 1em;
この辺りはどういうニュアンスで使ってますか？

2020-05-08 04:40 UTC, hide-a1 commented on src/app/home/home/home.component.scss
> +  margin-block-start: 1em;
とりあえず見た目をつくるためにコピーしてきた部分のスタイルもコピーしてきただけです。

2020-05-08 04:50 UTC, deerboy commented on src/app/home/home/home.component.scss
> +  margin-block-start: 1em;
なぜおいてるか理解できてない場合や必要がないなら消しましょう。コピペする際も一通り理解した上で実装しましょう👌

2020-05-08 04:53 UTC, hide-a1 commented on src/app/home/home/home.component.scss
> +  margin-block-start: 1em;
了解です！
一旦削除しましたので、ご確認お願いいたします。

2020-05-09 08:16 UTC, dninomiya approved these changes
GJ!

2020-05-09 08:16 UTC, merged